option('unsafe-recover-nil-uuid', type: 'boolean', value: false)
option('nuvoton-sdk', type: 'boolean', value: false,
       description: 'Enable Nuvoton SDK support')
option('unsafe-writable-connectivity',
       type: 'boolean',
       value: false,
       description: 'Allow writes to the Connectivity member of the au.com.codeconstruct.MCTP.Endpoint1 interface on endpoint objects')
option('tests', type: 'boolean', value: false)
option(
    'mctp-i3c-devices',
    type: 'array',
    value: [],
    description: 'Default I3C devices list. Each element: name=val|bus_num=val|pid_mask=val|device_pid=val|role=val|is_secondary_bus_owner=val|is_i3c_target=val'
)
option(
    'mctp-i3c-multiple-bo-with-diff-eids',
    type: 'boolean',
    value: true,
    description: 'Enable support for multiple I3C bus owners with different EIDs'
)
